# Tutorial Class

In [1]:
participants = ['John', 'Leila', 'Gregory', 'Cate']
participants

['John', 'Leila', 'Gregory', 'Cate']

In [3]:
print(participants[1])

Leila


In [6]:
print(participants[-2])

Gregory


In [7]:
# want to cate with Maria

participants[3] = 'Maria'
participants

['John', 'Leila', 'Gregory', 'Maria']

In [8]:
# delete Gregory

del participants[2]
participants

['John', 'Leila', 'Maria']

In [9]:
participants[2]

'Maria'

In [10]:
participants.append("Dwayne")
participants

['John', 'Leila', 'Maria', 'Dwayne']

In [11]:
participants.extend(['George', 'Catherine'])
participants

['John', 'Leila', 'Maria', 'Dwayne', 'George', 'Catherine']

In [16]:
print('The first participants is ' + participants[0] + '.')

The first participants is John.


In [17]:
len('Dophine')

7

In [19]:
len(participants)

6

In [21]:
# Slicing

participants[1:3]

['Leila', 'Maria']

In [22]:
participants[:2]

['John', 'Leila']

In [23]:
participants[4:]

['George', 'Catherine']

In [24]:
participants[-2:]

['George', 'Catherine']

In [25]:
participants.sort()
participants

['Catherine', 'Dwayne', 'George', 'John', 'Leila', 'Maria']

In [27]:
participants.sort(reverse=True)
participants

['Maria', 'Leila', 'John', 'George', 'Dwayne', 'Catherine']

In [28]:
numbers = [1,2,3,4]
numbers.sort()
numbers

[1, 2, 3, 4]

In [29]:
numbers.sort(reverse=True)
numbers

[4, 3, 2, 1]

In [30]:
# Tuples

x = (40,41,42)
x

(40, 41, 42)

In [31]:
y = 50,51,52
y

(50, 51, 52)

In [32]:
a,b,c, = 1,4,6
c

6

In [33]:
x[0]

40

In [35]:
List_1 = [x,y]
List_1

[(40, 41, 42), (50, 51, 52)]

In [39]:
(age, year_of_school) ="30,17".split(',')
print(age)
print(year_of_school)

30
17


In [41]:
def square_info(x):
    A = x ** 2
    P = 4 * x
    print("Area and perimeter:")
    return A,P

square_info(3)

Area and perimeter:


(9, 12)

In [42]:
# Dictionaries
dict = {'k1': 'Cat', 'k2': 'Dog', 'k3': 'Mouse', 'k4': 'Fish'}
dict

{'k1': 'Cat', 'k2': 'Dog', 'k3': 'Mouse', 'k4': 'Fish'}

In [44]:
dict['k1']

'Cat'

In [45]:
dict['k3']

'Mouse'

In [46]:
# add more keys

dict['k5'] = 'parrot'
dict

{'k1': 'Cat', 'k2': 'Dog', 'k3': 'Mouse', 'k4': 'Fish', 'k5': 'parrot'}

In [47]:
# replaces k2 Dog with squrrel

dict['k2'] = 'squrrel'
dict

{'k1': 'Cat', 'k2': 'squrrel', 'k3': 'Mouse', 'k4': 'Fish', 'k5': 'parrot'}

In [50]:
# Example 2 dict

dep_workers = {'dep_1': 'Peter', 'dep_2': ['Jennifer','Micheal','Tommy']}

In [51]:
dep_workers ['dep_2']

['Jennifer', 'Micheal', 'Tommy']

In [52]:
#for Loop i. e for every element n inthe list even:

even = [0,2,4,6,8,10,12,14,16,18,20]

for n in even:
    print(n)

0
2
4
6
8
10
12
14
16
18
20


In [53]:
#for Loop i. e another example for every element n inthe list even:

even = [0,2,4,6,8,10,12,14,16,18,20]

for n in even:
    print(n, end = " ")

0 2 4 6 8 10 12 14 16 18 20 

In [54]:
# While loop and Inreamenting

x = 0
while x <=20:
    print(x, end = " ")
    x = x + 2

0 2 4 6 8 10 12 14 16 18 20 

In [55]:
# While loop and Increamenting

x = 0
while x <=20:
    print(x, end = " ")
    x += 2

0 2 4 6 8 10 12 14 16 18 20 

In [56]:
#Create list with range()function

range(10)

range(0, 10)

In [57]:
# Python list function
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
range(3,7)

range(3, 7)

In [59]:
list(range(3,7))

[3, 4, 5, 6]

In [60]:
range(1,20,2)

range(1, 20, 2)

In [61]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [62]:
# Use conditional Statement and loops

for n in range(10):
    print(2 ** n, end = " ")

1 2 4 8 16 32 64 128 256 512 

In [63]:
for x in range(20):
    if x % 2 == 0:
        print(2 ** n, end = " ")
    else:
        print("odd", end = " ")

512 odd 512 odd 512 odd 512 odd 512 odd 512 odd 512 odd 512 odd 512 odd 512 odd 

In [65]:
x = 0,1,2

In [66]:
for item in x:
    print(item, end = " ")

0 1 2 

In [68]:
for item in range(len(x)):
    print(x[item], end = " ")

0 1 2 

In [77]:
# count Function

def count(numbers):
    total = 0
    for x in numbers:
        if x < 20:
            total += 1
    return total

In [78]:
list_1 =[1,3,7,15,23,43,56,98,17]

In [79]:
count(list_1)

5

# Iterating Over Dictionaries

In [3]:
# How much did jan spent in the supermarket?

# price*quantity
# box_of_Spagherti: 4*6 = 24
# lasgna: 5*10 = 40
# Hanburger: 2*0 = 0
# total Answer = 74


price = {
    "box_of_spagherti": 4,
    "lasgna": 5,
    "Handburger": 2
}
quantity ={
    "box_of_spagherti": 6,
    "lasgna":10,
    "Handburger": 0
}

money_spent = 0

for i in price:
    money_spent = money_spent + (price[i] * quantity[i])
    
print(money_spent)

74


In [1]:
list_1 = [1,2]
list_1

[1, 2]

In [2]:
list_2 = [34,45]
list_2

[34, 45]

In [3]:
list_1.extend(list_2)

# Import the relvant libraries

In [5]:
import numpy as np

# Declaring scalars ,vectors and matrices

# Scalars

In [6]:
s = 5
s

5

# Vectors

In [7]:
v = np.array([5, -2, 4])
v

array([ 5, -2,  4])

# Matrices

In [8]:
m = np.array([[5,12,6],[3,0,14]])
m

array([[ 5, 12,  6],
       [ 3,  0, 14]])

# Data types

In [11]:
type(s)

int

In [12]:
type(v)

numpy.ndarray

In [13]:
type(m)

numpy.ndarray

In [14]:
s_array = np.array(5)
s_array

array(5)

In [15]:
type(s_array)

numpy.ndarray

# Data Shape

In [16]:
m.shape

(2, 3)

In [17]:
a = np.array([[5,12,6],[-3,0,14]])
a

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [18]:
a.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [20]:
s = np.array([[5,3],[2,4]])
s

array([[5, 3],
       [2, 4]])

In [21]:
s.T

array([[5, 2],
       [3, 4]])

In [5]:
import pandas as pd

In [6]:
pd.__version__

'1.4.4'

In [7]:
import numpy as np

In [9]:
np.__version__

'1.21.5'

In [10]:
import pandas as pd

In [12]:
products = ['A','B','C','D']
products

['A', 'B', 'C', 'D']

In [13]:
type(products)

list

In [14]:
product_categories = pd.Series(products)
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [32]:
product_categories.dtype

dtype('O')

In [33]:
product_categories.size

4

In [15]:
type(product_categories)

pandas.core.series.Series

In [16]:
type(pd.Series(products))

pandas.core.series.Series

In [18]:
daily_rate_dollars = pd.Series([40,45,50,60])
daily_rate_dollars

0    40
1    45
2    50
3    60
dtype: int64

In [19]:
print(daily_rate_dollars)

0    40
1    45
2    50
3    60
dtype: int64


In [20]:
import numpy as np

In [21]:
array_a = np.array([10,20,30,40,50])
array_a

array([10, 20, 30, 40, 50])

In [22]:
type(array_a)

numpy.ndarray

In [29]:
series_a = pd.Series(array_a)
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [30]:
series_a.dtype

dtype('int64')

In [31]:
series_a.size

5

In [24]:
print(series_a)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [25]:
type(series_a)

pandas.core.series.Series

# Introduction to Pandas DataFrame

In [1]:
import pandas as pd

# Creating DataFrame from Scratch

#1: Construct a DataFrame from a dictionaries lists

In [7]:
data = {'ProductName':['Product A','Product B','Product C',], 'ProductPrice':[22250,16600,12500]}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

#2: Construct a DataFrame from a Dictionary of list + specify an index

In [11]:
data = {'ProductName':['Product A','Product B','Product C',], 'ProductPrice':[22250,16600,12500]}
df = pd.DataFrame(data, index = ['A','B','C'])
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [15]:
data = {'ProductName':['Product A','Product B','Product C',], 'ProductPrice':[22250,16600,12500]}
product_IDs = ['A','B','C']
df = pd.DataFrame(data, index = product_IDs)
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

#3: Construct a DataFrame from a List of Dictionaries

In [20]:
data = [{'ProductName':'Product A', 'ProductPrice':22250},
        {'ProductName':'Product B', 'ProductPrice':16600},
        {'ProductName':'Product C', 'productPrice':12500}]
df = pd.DataFrame(data)
df

ProductName  ProductPrice  productPrice
0   Product A       22250.0           NaN
1   Product B       16600.0           NaN
2   Product C           NaN       12500.0

In [21]:
data = [{'ProductName':'Product A','ProductPrice':22250},
        {'ProductName':'Product B','ProductPrice':16600},
        {'ProductName':'Product C','productPrice':[12500,100000]}]
df = pd.DataFrame(data)
df

ProductName  ProductPrice     productPrice
0   Product A       22250.0              NaN
1   Product B       16600.0              NaN
2   Product C           NaN  [12500, 100000]

In [ ]:
data = [{'ProductName':'Product A':'ProductPrice':22250},
        {'ProductName':'Product B':'ProductPrice':16600},
        {'ProductName':'Product C':'productPrice':12500}
        {'ProductName':'Product D'}]
df = pd.DataFrame(data)
df

#4: construct a DataFrame from a list of list

In [25]:
data = [['Product A', 22250],['Product B',16600],['Product C',12500]]
df = pd.DataFrame(data)
df

0      1
0  Product A  22250
1  Product B  16600
2  Product C  12500

In [26]:
data = [['Product A', 22250],['Product B',16600],['Product C',12500,5000]]
df = pd.DataFrame(data)
df

0      1       2
0  Product A  22250     NaN
1  Product B  16600     NaN
2  Product C  12500  5000.0

In [27]:
data = [['Product A', 22250],['Product B',16600],['Product C',12500]]
df = pd.DataFrame(data)
df

0      1
0  Product A  22250
1  Product B  16600
2  Product C  12500

In [28]:
df.columns = ['ProductName','ProductPrice']
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

In [29]:
df.index = ['A','B','C']
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

# 5: Construction of DataFrame in Proffesional Way

In [30]:
df = pd.DataFrame(data = [['Product A', 22250],['Product B',16600],['Product C',12500]],
                  columns = ['ProductName','ProductPrice'],
                  index = ['A','B','C'])
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [31]:
df.shape

(3, 2)

# Importing a text files in python (with open ())

In [7]:
filename = 'Montgomery_Fleet_Equipment_Inventory_FA_PART_1_START.csv'

file = open(filename, mode = 'r')
text = file.read()
text

FileNotFoundError: [Errno 2] No such file or directory: 'Montgomery_Fleet_Equipment_Inventory_FA_PART_1_START.csv'

In [ ]:
type(text)

In [9]:
import pandas as pd

In [1]:
import pandas as pd

In [11]:
import pandas as pd

In [12]:
dataset = pd.read_csv('Video_Games_Sales_as_at_22_Dec_2016.csv')

In [13]:
dataset.head()

Name Platform  Year_of_Release         Genre Publisher  \
0                Wii Sports      Wii           2006.0        Sports  Nintendo   
1         Super Mario Bros.      NES           1985.0      Platform  Nintendo   
2            Mario Kart Wii      Wii           2008.0        Racing  Nintendo   
3         Wii Sports Resort      Wii           2009.0        Sports  Nintendo   
4  Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  \
0     41.36     28.96      3.77         8.45         82.53          76.0   
1     29.08      3.58      6.81         0.77         40.24           NaN   
2     15.68     12.76      3.79         3.29         35.52          82.0   
3     15.61     10.93      3.28         2.95         32.77          80.0   
4     11.27      8.89     10.22         1.00         31.37           NaN   

   Critic_Count  User_Score  User_Count Developer Rating  
0          51.0         8.0       322.0  Nintendo      E  
1           NaN         NaN         NaN       NaN    NaN  
2          73.0         8.3       709.0  Nintendo      E  
3          73.0         8.0       192.0  Nintendo      E  
4           NaN         NaN         NaN       NaN    NaN

In [14]:
import pandas as pd

In [15]:
data =pd.read_csv('animal.csv')

In [16]:
data

Unnamed: 0 animal  Age  visit pririoty
0          a    cat  2.5      1      yes
1          b    cat  3.0      3      yes
2          c  snake  0.5      2       no
3          d    dog  NaN      3      yes
4          e    dog  5.0      2       no
5          f    cat  1.5      3       no
6          g  snake  4.5      1       no
7          h    cat  NaN      1      yes
8          i    dog  7.0      2       no
9          j    dog  3.0      1       no

In [17]:
type(data)

pandas.core.frame.DataFrame

In [18]:
type(dataset)

pandas.core.frame.DataFrame

# Iterable over Range

In [1]:
t = (1,2,3,4)
t

(1, 2, 3, 4)

In [2]:
l = [10,12,14,16]
l

[10, 12, 14, 16]

In [3]:
s ='abcd'
s

'abcd'

In [4]:
for i in t:
    print(i, end = " ")

1 2 3 4 

In [7]:
range(5)

range(0, 5)

In [9]:
for i in range(5):
    print(i, end = " ")

0 1 2 3 4 

# Nest for Loops in python

In [11]:
for i in range(2):
    print(i)

0
1


In [12]:
for j in range(5):
    print(j)

0
1
2
3
4


In [13]:
for i in range(2):
    for j in range(5):
        print(j)

0
1
2
3
4
0
1
2
3
4


In [14]:
for i in range(2):
    for j in range(5):
        print([i,j])

[0, 0]
[0, 1]
[0, 2]
[0, 3]
[0, 4]
[1, 0]
[1, 1]
[1, 2]
[1, 3]
[1, 4]


In [16]:
for i in ['product A','product B']:
    for j in range(5):
        print([i,j])

['product A', 0]
['product A', 1]
['product A', 2]
['product A', 3]
['product A', 4]
['product B', 0]
['product B', 1]
['product B', 2]
['product B', 3]
['product B', 4]


In [20]:
products = ['product A','product B']
exp_sales = [10000,11000,12000,13000,14000]

In [21]:
for i in products:
    for j in exp_sales:
        print([i,j])

['product A', 10000]
['product A', 11000]
['product A', 12000]
['product A', 13000]
['product A', 14000]
['product B', 10000]
['product B', 11000]
['product B', 12000]
['product B', 13000]
['product B', 14000]


# Triple Nested for Loops

In [28]:
products = ['Product A','Product B']
exp_sales = [10000,11000,12000,13000,14000]

In [29]:
time_horizon = (1,3,12)

In [31]:
# Pls note the stated formular can even be used in 3,4,5,6 nested loops

for i in products:
    for j in exp_sales:
        for k in time_horizon:
            print([i,j*k])

['Product A', 10000]
['Product A', 30000]
['Product A', 120000]
['Product A', 11000]
['Product A', 33000]
['Product A', 132000]
['Product A', 12000]
['Product A', 36000]
['Product A', 144000]
['Product A', 13000]
['Product A', 39000]
['Product A', 156000]
['Product A', 14000]
['Product A', 42000]
['Product A', 168000]
['Product B', 10000]
['Product B', 30000]
['Product B', 120000]
['Product B', 11000]
['Product B', 33000]
['Product B', 132000]
['Product B', 12000]
['Product B', 36000]
['Product B', 144000]
['Product B', 13000]
['Product B', 39000]
['Product B', 156000]
['Product B', 14000]
['Product B', 42000]
['Product B', 168000]


In [39]:
# Pls note the stated formular can even be used in 3,4,5,6 nested loops or another style 
# of above for tripel by substitution nested formular

for prod in products:
    for sales in exp_sales:
        for t_hor in time_horizon:
            print([prod,sales*t_hor])

['Product A', 10000]
['Product A', 30000]
['Product A', 120000]
['Product A', 11000]
['Product A', 33000]
['Product A', 132000]
['Product A', 12000]
['Product A', 36000]
['Product A', 144000]
['Product A', 13000]
['Product A', 39000]
['Product A', 156000]
['Product A', 14000]
['Product A', 42000]
['Product A', 168000]
['Product B', 10000]
['Product B', 30000]
['Product B', 120000]
['Product B', 11000]
['Product B', 33000]
['Product B', 132000]
['Product B', 12000]
['Product B', 36000]
['Product B', 144000]
['Product B', 13000]
['Product B', 39000]
['Product B', 156000]
['Product B', 14000]
['Product B', 42000]
['Product B', 168000]


In [42]:
# Pls note the stated formular can even be used in 3,4,5,6 nested loops or another style 
# of above for tripel by substitution nested formular

for prod in products:
    for sales in exp_sales:
        for t_hor in time_horizon:
            print('expected sales for period {0} month {s} for (1)')= ${'sales'}'.format(t_hor, prod, sales = sales * t_hor))

SyntaxError: cannot assign to function call (2169570736.py, line 7)

# List Comprehension

In [44]:
# this is the one professional use most is easy to understand and to write

numbers = [1,13,4,5,63,100]
numbers

[1, 13, 4, 5, 63, 100]

In [45]:
new_numbers = []

for n in numbers:
    new_numbers.append(n * 2)
    
print(new_numbers)

[2, 26, 8, 10, 126, 200]


In [46]:
new_numbers =[n * 2 for n in new_numbers]
print(new_numbers)

[4, 52, 16, 20, 252, 400]


In [1]:
for i in range(2):
    for j in range(5):
        print(i + j, end, " ")

NameError: name 'end' is not defined

# Pulling data from Public APIs - GET Request

In [15]:
base_url = "https://data.fixer.io/api/latest"

# Extracting data on currency exchangr rate

# Sending a GET Request

In [16]:
import requests

In [18]:
response = requests.get(base_url)

# Investigating the response

In [19]:
response.ok

True

In [20]:
response.status_code

200

In [21]:
# body of the text
response.text

'{\n  "success": false,\n  "error": {\n    "code": 101,\n    "type": "missing_access_key",\n    "info": "You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]"\n  }\n}\n'

In [22]:
# Body of the text alternatively

response.content

b'{\n  "success": false,\n  "error": {\n    "code": 101,\n    "type": "missing_access_key",\n    "info": "You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]"\n  }\n}\n'

# Handling the JSON

In [24]:
response.json()

{'success': False,
 'error': {'code': 101,
  'type': 'missing_access_key',
  'info': 'You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]'}}

In [25]:
type(response.json())

dict

In [27]:
import json

In [28]:
json.dumps(response.json(), indent = 4)

'{\n    "success": false,\n    "error": {\n        "code": 101,\n        "type": "missing_access_key",\n        "info": "You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]"\n    }\n}'

In [31]:
print(json.dumps(response.json(), indent = 4))

{
    "success": false,
    "error": {
        "code": 101,
        "type": "missing_access_key",
        "info": "You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]"
    }
}


In [33]:
response.json().keys()

dict_keys(['success', 'error'])

# Dimension and Squeez function

In [2]:
matrix_d =([[1,1,1,2,0],[3,6,6,7,4],[4,5,0,0]])
matrix_d

[[1, 1, 1, 2, 0], [3, 6, 6, 7, 4], [4, 5, 0, 0]]

In [3]:
type(matrix_d[0:0])

list